# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "docker_context",
    "rust",
    "line_break",
    "env_var",
    "cmd_duration",
    "memory_usage",
    "jobs",
    "character",
]

[env_var]
variable = "SHELL"
default = "unknown shell"
style = "bold green"

[username]
disabled = false
show_always = true
style_root = "bold red"
style_user = "cyan"

[hostname]
prefix = "("
suffix = ")"
style = "bold red"
ssh_only = false
disabled = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = 75
symbol = ""
separator = "/"
style = "bold red"

[jobs]
symbol = "+ "
threshold = 1

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"
error_symbol = "✖"

[battery]
full_symbol = "☣ "
charging_symbol = "⚡️"
discharging_symbol = "☠ "

[[battery.display]]
threshold = 10
style = "bold red"

[cmd_duration]
min_time = 500

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
